### ISSUE TITLE
Добавить удаление вишлиста

### ISSUE THREAD

**Issue by VolegzhaninaEM** [stas12312/wishlists#32]
Сейчас нет возможности удаления вишлиста, как мне кажется это важно)
![image](https://github.com/stas12312/wishlists/assets/92241355/4bf9f05f-fcf0-404a-8b1c-d3cd444c1b10)

**Comment by stas12312** [comment]
@VolegzhaninaEM метод добавил

**Comment by VolegzhaninaEM** [comment]
- [ ] Добавить всплывашку с подтверждением "Вы действительно хотите удалить этот список?"
- [ ] Прикрутить метод + обновлять список после удаления вишлиста
